name: OWASP ZAP Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build   # if you need a build step
      - run: npm start &     # or: npm run dev &
        env:
          PORT: 3000

      - name: Wait for server to be ready
        run: |
          timeout 60 bash -c \
            'until curl -sSf http://localhost:3000 > /dev/null; do sleep 2; done'

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'   # now reachable
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: true
          artifact_name: 'zap-baseline-report'
