name: OWASP ZAP Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write      # only needed if allow_issue_writing=true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ── Baseline scan (fast, passive) -----------------------------
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0   # pin to latest stable
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000/'   # <-- change to your URL
          rules_file_name: '.zap/rules.tsv'        # optional custom rules
          cmd_options: '-a'                        # active scan disabled (baseline)
          allow_issue_writing: true                # creates GitHub issues for new alerts
          artifact_name: 'zap-baseline-report'     # HTML report stored as artifact

      # ── Full Scan(Deeper and more comprehensive ----------
      # - name: Run OWASP ZAP Full Scan
      #   uses: zaproxy/action-full-scan@v0.10.0
      #   with:
      #     target: 'http://localhost:3000/'
      #     artifact_name: 'zap-full-report'
